name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: app-modbus

      - name: Initialize
        working-directory: app-modbus
        run: |
          west init -l .
          west update

      - name: Build firmware
        working-directory: app-modbus
        run: |
          west build -b nucleo_h753zi

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: app-modbus/build/zephyr/zephyr.*
          retention-days: 14
